#include "evaluation.h"

Value* get_builtin_add();
Value* get_builtin_branch();
Value* get_builtin_define();
Value* get_builtin_display();
Value* get_builtin_eq();
Value* get_builtin_gt();
Value* get_builtin_gte();
Value* get_builtin_is_equal();
Value* get_builtin_is_list();
Value* get_builtin_lambda();
Value* get_builtin_let();
Value* get_builtin_let_ex();
Value* get_builtin_list();
Value* get_builtin_lt();
Value* get_builtin_lte();
Value* get_builtin_minus();
Value* get_builtin_mul();
